// Reads a build-time snapshot of the Medium feed and processes it into the
// shape the rest of the app expects. The snapshot is generated by
// scripts/fetch-medium.js (wired into `prebuild`) so the live RSS feed is
// only hit once per build instead of once per Next.js worker × per route.

import fs from 'fs';
import path from 'path';

const SNAPSHOT_PATH = path.join(process.cwd(), 'lib', 'medium-snapshot.json');

const formatDate = (dateString) => {
  if (!dateString) return null;
  const date = new Date(dateString);
  return isNaN(date.getTime()) ? null : date;
};

const stripHtml = (html) => {
  if (!html) return '';
  return html.replace(/<\/p>/gi, '\n').replace(/<[^>]*>/g, '').trim();
};

const createSlug = (title) => {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .substring(0, 100);
};

const createExcerpt = (content, minWords = 250) => {
  if (!content) return '';

  let filteredContent = content.replace(/<h[1-4][^>]*>.*?<\/h[1-4]>/gi, '');
  filteredContent = filteredContent.replace(/<figure[^>]*>.*?<\/figure>/gi, '');
  filteredContent = filteredContent.replace(/<figcaption[^>]*>.*?<\/figcaption>/gi, '');
  filteredContent = filteredContent.replace(/Photo by.*?<\/p>/gi, '');
  filteredContent = filteredContent.replace(/Image by.*?<\/p>/gi, '');
  filteredContent = filteredContent.replace(/Credit:.*?<\/p>/gi, '');

  const plainText = stripHtml(filteredContent);
  const paragraphs = plainText.split(/\n+/).filter((p) => p.trim().length > 0);

  let startIndex = 0;
  if (paragraphs.length > 1 && paragraphs[0].trim().length < 100) {
    startIndex = 1;
  }

  const contentParagraphs = paragraphs.slice(startIndex);

  let selectedParagraphs = [];
  let wordCount = 0;

  for (const paragraph of contentParagraphs) {
    const cleanParagraph = paragraph.trim();
    if (!cleanParagraph) continue;
    if (cleanParagraph.length < 30) continue;
    if (/^(Photo|Image|Credit|Photo by|Image by|Source:|Via)/i.test(cleanParagraph)) continue;

    const words = cleanParagraph.split(/\s+/).filter((w) => w.length > 0);

    selectedParagraphs.push(cleanParagraph);
    wordCount += words.length;

    if (wordCount >= minWords) {
      break;
    }
  }

  if (selectedParagraphs.length === 0) {
    return 'Read the full article on Medium...';
  }

  return selectedParagraphs.join('\n\n');
};

const extractThumbnail = (content) => {
  if (!content) return null;
  const imgMatch = content.match(/<img[^>]+src="([^"]+)"[^>]*>/i);
  return imgMatch ? imgMatch[1] : null;
};

const extractFirstThreeParagraphs = (content) => {
  if (!content) return [];

  let filteredContent = content.replace(/<h[1-4][^>]*>.*?<\/h[1-4]>/gi, '');
  filteredContent = filteredContent.replace(/<figure[^>]*>.*?<\/figure>/gi, '');
  filteredContent = filteredContent.replace(/<figcaption[^>]*>.*?<\/figcaption>/gi, '');
  filteredContent = filteredContent.replace(/Photo by.*?<\/p>/gi, '');
  filteredContent = filteredContent.replace(/Image by.*?<\/p>/gi, '');
  filteredContent = filteredContent.replace(/Credit:.*?<\/p>/gi, '');

  const plainText = stripHtml(filteredContent);
  const paragraphs = plainText.split(/\n+/).filter((p) => p.trim().length > 0);

  let startIndex = 0;
  if (paragraphs.length > 1 && paragraphs[0].trim().length < 100) {
    startIndex = 1;
  }

  return paragraphs.slice(startIndex, startIndex + 3);
};

let _cached = null;

function loadSnapshot() {
  if (_cached) return _cached;

  try {
    if (!fs.existsSync(SNAPSHOT_PATH)) {
      console.warn(`Medium snapshot not found at ${SNAPSHOT_PATH}. Run 'node scripts/fetch-medium.js'.`);
      _cached = [];
      return _cached;
    }

    const raw = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, 'utf8'));

    _cached = raw.map((item) => {
      const content = item.content || '';
      const title = item.title || 'Untitled Article';
      return {
        title,
        link: item.link,
        slug: createSlug(title),
        pubDate: item.pubDate,
        formattedDate: formatDate(item.pubDate),
        description: createExcerpt(content),
        firstThreeParagraphs: extractFirstThreeParagraphs(content),
        thumbnail: extractThumbnail(content),
        content,
      };
    });

    return _cached;
  } catch (err) {
    console.error('Failed to load Medium snapshot:', err.message);
    _cached = [];
    return _cached;
  }
}

export async function getMediumArticles() {
  return loadSnapshot();
}

export async function getArticleBySlug(slug) {
  const articles = loadSnapshot();
  return articles.find((article) => article.slug === slug) || null;
}

export async function getRecommendedArticles(currentSlug) {
  const allArticles = loadSnapshot();

  const otherArticles = allArticles.filter((article) => article.slug !== currentSlug);

  for (let i = otherArticles.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [otherArticles[i], otherArticles[j]] = [otherArticles[j], otherArticles[i]];
  }

  return otherArticles.slice(0, 3);
}
